# Generated by Django 5.0.1 on 2024-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finch",
            name="does_it_fly",
        ),
        migrations.AddField(
            model_name="finch",
            name="favorite_music_genre",
            field=models.CharField(default="Country", max_length=100),
            preserve_default=False,
        ),
    ]
